export const INITIAL_HOSPITALS = [
  { name: "Dhaka Medical College Hospital", location: "Ramna, Dhaka", phone: "01711-222222", type: "hospital" },
  { name: "Bangabandhu Sheikh Mujib Medical University", location: "Shahbag, Dhaka", phone: "02-9661068", type: "hospital" },
  { name: "Square Hospital", location: "Panthapath, Dhaka", phone: "10616", type: "hospital" },
  { name: "Evercare Hospital", location: "Bashundhara, Dhaka", phone: "10678", type: "hospital" },
  { name: "United Hospital", location: "Gulshan, Dhaka", phone: "10666", type: "hospital" },
  { name: "Labaid Specialized Hospital", location: "Dhanmondi, Dhaka", phone: "10606", type: "hospital" },
  { name: "Ibn Sina Specialized Hospital", location: "Dhanmondi, Dhaka", phone: "10615", type: "hospital" },
  { name: "Chittagong Medical College Hospital", location: "Chittagong", phone: "031-619400", type: "hospital" },
  { name: "Rajshahi Medical College Hospital", location: "Rajshahi", phone: "0721-772150", type: "hospital" },
  { name: "Sylhet MAG Osmani Medical College Hospital", location: "Sylhet", phone: "0821-713242", type: "hospital" },
  { name: "Khulna Medical College Hospital", location: "Khulna", phone: "041-760350", type: "hospital" },
  { name: "Sher-e-Bangla Medical College Hospital", location: "Barisal", phone: "0431-2173500", type: "hospital" },
  { name: "Rangpur Medical College Hospital", location: "Rangpur", phone: "0521-62150", type: "hospital" },
  { name: "Mymensingh Medical College Hospital", location: "Mymensingh", phone: "091-62295", type: "hospital" },
  { name: "Comilla Medical College Hospital", location: "Comilla", phone: "081-65562", type: "hospital" },
  { name: "Bangladesh Red Crescent Society", location: "Moghbazar, Dhaka", phone: "02-9330188", type: "blood_bank" },
  { name: "Sandhani (DMCH Unit)", location: "Dhaka Medical College, Dhaka", phone: "01711-123456", type: "blood_bank" },
  { name: "Badhon (DU Unit)", location: "Dhaka University, Dhaka", phone: "01511-123456", type: "blood_bank" },
  { name: "Quantum Foundation", location: "Shantinagar, Dhaka", phone: "02-9351969", type: "blood_bank" },
  { name: "Mukti Blood Bank", location: "Dhaka", phone: "01711-567890", type: "blood_bank" },
  { name: "Police Blood Bank", location: "Rajarbag, Dhaka", phone: "01713-398487", type: "blood_bank" },
  { name: "Fatema Blood Bank", location: "Dhaka", phone: "01711-112233", type: "blood_bank" },
  { name: "Life Blood Bank", location: "Chittagong", phone: "01819-123456", type: "blood_bank" },
  { name: "Sandhani (CMCH Unit)", location: "Chittagong Medical College, Chittagong", phone: "01711-223344", type: "blood_bank" },
  { name: "Badhon (CU Unit)", location: "Chittagong University, Chittagong", phone: "01511-223344", type: "blood_bank" }
];
