import { Donor } from './types';

export const MOCK_DONORS: Donor[] = [
  {
    id: '1',
    name: 'আরিফ হোসেন',
    bloodGroup: 'A+',
    location: 'ঢাকা, বাংলাদেশ',
    phone: '01712345678',
    lastDonated: '৩ মাস আগে',
    image: 'https://picsum.photos/seed/donor1/400/400',
    available: true,
    facebookUrl: 'https://facebook.com',
    whatsappNumber: '01712345678',
  },
  {
    id: '2',
    name: 'তানজিলা আক্তার',
    bloodGroup: 'O+',
    location: 'চট্টগ্রাম, বাংলাদেশ',
    phone: '01812345678',
    lastDonated: '৫ মাস আগে',
    image: 'https://picsum.photos/seed/donor2/400/400',
    available: true,
    whatsappNumber: '01812345678',
  },
  {
    id: '3',
    name: 'রাকিবুল ইসলাম',
    bloodGroup: 'B+',
    location: 'সিলেট, বাংলাদেশ',
    phone: '01912345678',
    lastDonated: '১ মাস আগে',
    image: 'https://picsum.photos/seed/donor3/400/400',
    available: false,
  },
  {
    id: '4',
    name: 'সুমাইয়া বিনতে',
    bloodGroup: 'AB+',
    location: 'রাজশাহী, বাংলাদেশ',
    phone: '01612345678',
    lastDonated: '৬ মাস আগে',
    image: 'https://picsum.photos/seed/donor4/400/400',
    available: true,
  },
  {
    id: '5',
    name: 'মেহেদী হাসান',
    bloodGroup: 'O-',
    location: 'খুলনা, বাংলাদেশ',
    phone: '01512345678',
    lastDonated: '২ মাস আগে',
    image: 'https://picsum.photos/seed/donor5/400/400',
    available: true,
  },
  {
    id: '6',
    name: 'ফাতেমা তুজ জোহরা',
    bloodGroup: 'A-',
    location: 'বরিশাল, বাংলাদেশ',
    phone: '01312345678',
    lastDonated: '৪ মাস আগে',
    image: 'https://picsum.photos/seed/donor6/400/400',
    available: true,
  },
];
